# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-18 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='Tags',
            field=models.ManyToManyField(to='news.Tags'),
        ),
    ]
