# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-18 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200518_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_image',
        ),
        migrations.AlterField(
            model_name='article',
            name='Tags',
            field=models.ManyToManyField(to='news.Tags'),
        ),
    ]
