# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-18 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200518_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='articles/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Tags',
            field=models.ManyToManyField(to='news.Tags'),
        ),
    ]
