# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-21 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200521_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Tags',
            field=models.ManyToManyField(to='news.Tags'),
        ),
        migrations.AlterField(
            model_name='article',
            name='editor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='post',
            field=tinymce.models.HTMLField(),
        ),
    ]
